var products2=[
    
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://cdn-images.farfetch-contents.com/16/04/71/52/16047152_31633872_600.jpg ",
        name: "Palm Angels palm tree high-top sneakers ",
        brand: "PALM ANGLE",
        category: "SHOES",
        price_now: 9999,
        strikedoffprice: 12000,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://cdn-images.farfetch-contents.com/17/38/87/94/17388794_36294381_600.jpg",
        name: " Off-White Arrows leather-trim backpack",
        brand: "OFF WHITE",
        category: "BAG",
        price_now: 779,
        strikedoffprice: 1299,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://content.shop4reebok.com/static/Product-GK9175/reebok_GK9175_1.jpg.plp",
        name: "MEN'S REEBOK TRAINING FOUNDATION  PANTS  ",
        brand: "REEBOK",
        category: "PANT",
        price_now: 1019,
        strikedoffprice: 1699,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://content.shop4reebok.com/static/Product-GK9176/reebok_GK9176_1.jpg.plp ",
        name: "MEN'S REEBOK TRAINING FOUNDATION PANTS  ",
        brand: "REEBOK",
        category: "PANT",
        price_now: 1019,
        strikedoffprice: 1699,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://cdn-images.farfetch-contents.com/16/86/53/38/16865338_36146527_600.jpg",
        name: "Palm Angels slogan-print tote bag ",
        brand: "PALM ANGLE",
        category: "BAG",
        price_now: 1575,
        strikedoffprice: 3499,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            " https://content.shop4reebok.com/static/Product-G57776/reebok_G57776_1.jpg.plp ",
        name: "  MEN'S REEBOK RUNNING ZTAUR RUN SHOES ",
        brand: "REEBOK",
        category: "SHOES",
        price_now: 3449,
        strikedoffprice: 4999,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            " https://cdn-images.farfetch-contents.com/16/32/31/49/16323149_37142236_600.jpg ",
        name: "MAD Paris MAD EMERALDS DAYTONA",
        brand: "MAD PARIS",
        category: "WATCH",
        price_now: 749,
        strikedoffprice: 1499,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://cdn-images.farfetch-contents.com/17/72/28/77/17722877_37116982_600.jpg",
        name: "MAD Paris Nobile quartz 43mm",
        brand: "MAD PARIS",
        category: "WATCH",
        price_now: 1149,
        strikedoffprice: 2299,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            " https://content.shop4reebok.com/static/Product-EX4287/reebok_EX4287_1.jpg.plp  ",
        name: " MEN'S REEBOK RUNNING GENESIS RUNNER SHOE  ",
        brand: "REEBOK",
        category: "SHOES",
        price_now: 1620,
        strikedoffprice: 3599,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://content.shop4reebok.com/static/Product-G57705/reebok_G57705_1.jpg.plp",
        name: "UNISEX REEBOK CLASSICS  BASKETBALL SHOES",
        brand: "REEBOK",
        category: "SHOES",
        price_now: 3919,
        strikedoffprice: 5599,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            " https://cdn-images.farfetch-contents.com/17/29/77/93/17297793_36378668_600.jpg",
        name: " Gucci Eyewear aviator-frame sunglasses ",
        brand: "GUCCI",
        category: "SUNGLASSES",
        price_now: 2779,
        strikedoffprice: 4299,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://cdn-images.farfetch-contents.com/17/29/93/01/17299301_36471919_600.jpg",
        name: "Gucci Eyewear aviator-frame sunglasses",
        brand: "GUCCI",
        category: "SUNGLASSES",
        price_now: 3490,
        strikedoffprice: 4999,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            " https://cdn-images.farfetch-contents.com/17/75/27/86/17752786_37287322_600.jpg  ",
        name: "Gucci Strawberry Gucci print T-shirt ",
        brand: "GUCCI",
        category: "T-SHIRT",
        price_now: 3499,
        strikedoffprice: 4999,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://cdn-images.farfetch-contents.com/17/60/50/63/17605063_36598566_600.jpg ",
        name: "Gucci bleach-effect tapered-leg denim jeans",
        brand: "GUCCI",
        category: "PANT",
        price_now: 1399,
        strikedoffprice: 2799,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://cdn-images.farfetch-contents.com/15/40/06/66/15400666_27114541_600.jpg",
        name: "Gucci Ace GG Supreme sneaker",
        brand: "GUCCI",
        category: "SHOES",
        price_now: 1575,
        strikedoffprice: 3499,
        Symbol: "₹",
    },
    {
        pid: 5,
        price_was: 1000,
        img_src:
            "https://content.shop4reebok.com/static/Product-HC3528/reebok_HC3528_1.jpg.plp",
        name: "MEN'S REEBOK TRAINING BASIC POLO TEE",
        brand: "REEBOK",
        category: "T-SHIRT",
        price_now: 779,
        strikedoffprice: 1299,
        Symbol: "₹",
    },
    {
        pid: 5,
        img_src:
            "https://content.shop4reebok.com/static/Product-FW0344/reebok_FW0344_1.jpg.plp",
        name: "Gucci logo print hoodie",
        brand: "GUCCI",
        category: "SHOES",
        price_now: 1620,
        price_was: 1000,
        strikedoffprice: 3599,
        Symbol: "₹",
    },
]
console.log(JSON.stringify(products2))
